### ISSUE TITLE
Invoke-SSHCommand should allow for a timeout

### ISSUE THREAD

**Issue by MikeMM70** [darkoperator/Posh-SSH#9] opened 2015-02-06 16:27 UTC
I'm writing a script to check hardware status on our Fortigate firewalls and I have run into a problem:
If there is a problem with the flash media on the unit it will hang the "get hardware status" command until the unit is power cycled.  This in turn freezes the script.  Control-C does not work to stop the script and control-break stops it the script and closes the Powershell window.  If there was a set-able time out on the invoke command it would allow the script to continue.  Hopefully this is something you can implement, I know you rely on an external .net assembly. 

Thank you for creating Posh-SSH, it is turning out to be quite helpful.

**Comment by darkoperator** [comment] 2015-02-20 17:13
I think I found a way for it, will have to re-write the entire command to make it work. But it is doable

**Comment by darkoperator** [comment] 2015-03-18 23:03
Feature added, please test release 1.7 pushed out today.

**Comment by MikeMM70** [comment] 2015-03-23 20:18
In my testing the -TimeOut worked well, caused no problems if execution
completed in time and gave an exception if it ran too long.  Might be good
to document that the integer -TimeOut takes is measured in seconds just for
clarity.  Some people might ask if it isn't in the help.

One thing I saw was that might cause problems was if you set a variable to
the output of Invoke-SSHCommand and an exception was thrown on an iteration
after a successfully completed iteration, the variable will still contain
the contents of the successful iteration's output.

Try {
        $status = invoke-sshcommand -SessionId $session.SessionId -command
'get hardware status' -timeout 30
        }
Catch [Renci.SshNet.Common.SshOperationTimeoutException] {
            Write-Host 'Caught:  SSH Command Timed Out ' $status
-ForegroundColor Red -BackgroundColor White}

So if the previous iteration was successful $status would still contain
@{Output=Some output; Error=; ExitStatus=0; Host=192.168.1.1} from the
previous loop through after the exception was thrown.  I think this might
cause some people problems, they may expect the $Status.Error property to
be TimeOut or similar (and maybe $Status.ExitStatus to be -1?  Might be
best to leave ExitStatus as 0).  I don't know if you could safely capture
the Output of the invoke, might just be safer to set that to $Null.

Michael M.

**Comment by darkoperator** [comment] 2015-03-23 20:58
Well you control status so you should be able to just initialize the var. on the error it is the command shell error not the general error of execution in PowerShell you would look at $_ inside the catch or $Error[0]

**Comment by darkoperator** [comment] 2015-03-23 21:00
by status is that you created that var in the session scope, the var inside the function is in another scope and is not passed to status in the case of a timeout, you are catching the exception before the value is set.

**Comment by darkoperator** [comment] 2015-03-23 21:05
you are correct I missed the parameter info when I moved to XML help will update that now.

**Comment by darkoperator** [comment] 2015-03-23 21:14
updated the help in master branch

**Comment by darkoperator** [comment] 2015-03-24 13:41
Closing since I believe it is working as intended. you can reopen if needed. 

```PowerShell
$commands = "ls -la /tmp", "ifconfig", "uname -a"

foreach ($command in $commands)
{

    Try {
        $status = $null
        # if a timeout happens the exception is thrown and it is not saved to status.
        # that is why you would handle it with Try{}Catch{}Finally{}.
        # You can initialize the variable before every loop.
        $status = invoke-sshcommand -SessionId $session.SessionId -command $command -timeout 30
    }
    Catch [Renci.SshNet.Common.SshOperationTimeoutException] {
            Write-Host 'Caught:  SSH Command Timed Out '
    }
}
```

**Closed by darkoperator** 2015-03-24 13:41 UTC
Labels: enhancement
